component_management:
  individual_components:
    - component_id: main
      name: main
      paths:
        - main.py

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: true
